# Site settings
title: nomadli
email: dzym79@qq.com
description: nomadli's blog
baseurl: ""
url: "http://nomadli.github.io/"
github_username:  nomadli
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
